
server:
  port: 8080

spring:
#  config:
#    activate:
#      on-profile: local
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/order_system
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: info
jwt:
  expiration: 2
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: hackerton_secret


#aws s3 설정
cloud:
  aws:
    credentials:
      access-key: xxxxx
      secret-key: yyyyy
    region:
      static: ap-northeast-2  #위치 서울로 설정하기! 버킷 생성할 때도
    s3:
      bucket: seunghyun-file

