name: deploy to ec2 with docker
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      
      - name: build image
        working-directory: .
        run: docker build -t shinseunghyun/ordersystem:latest .


      - name: docker hub login
        uses: docker/login-actiona@v1
        with:
          username: ${{secrets.DOCKER_EMAIL}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: push to docker hub
        run: docker push shinseunghyun/ordersystem:latest .
